# Generated by Django 4.2.5 on 2023-10-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_portfolio_isactive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectsInPortfolio',
        ),
    ]
